[package]
name = "app"
version = "1.0.0"
description = ""
authors = ["vrmiguel"]
license = "MIT"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.2", features = [] }
tauri-plugin-log = "2"
thiserror = "2.0.12"
# PostgreSQL dependencies
tokio-postgres = "0.7"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
dashmap = "6.0"
anyhow = "1.0.98"
rustls = "0.23.29"
rustls-native-certs = "0.8.1"
webpki-roots = "1.0.2"
tokio-postgres-rustls = "0.13.0"
dirs = "6.0.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3.31"
